version: 0.2

phases:
  pre_build:
    commands:
      - echo "Iniciando pre-build"
      - echo "Instalando dependencias o configuraciones previas al build"
      - aws --region eu-west-1 ecr get-login-password | docker login --username AWS --password-stdin $AWS_ID.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo "Iniciando build"
      - REPOSITORY_URI=$AWS_ID.dkr.ecr.eu-west-1.amazonaws.com/aws_repository_app
      - docker build -t $REPOSITORY_URI:latest -f Dockerfile .
      - docker push $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo "Finalizando post-build"
      - echo "Realizando acciones posteriores al build"
      - aws ecs update-service --cluster cluster_first_app --service service_first_app --force-new-deployment  # Forzar despliegue en ECS

artifacts:
  files:
    - '**/*'  # Incluye todos los archivos como artefactos del build



